/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import datos.UsuarioJDBC;
import dominio.Usuario;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.JOptionPane;

/**
 *
 * @author W10
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
   
    
    public login() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcontra = new javax.swing.JLabel();
        textboxus = new javax.swing.JTextField();
        textboxpw = new javax.swing.JPasswordField();
        btnolvide = new javax.swing.JButton();
        btning = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtuser1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtcontra.setForeground(new java.awt.Color(255, 255, 255));
        txtcontra.setText("contraseña");
        getContentPane().add(txtcontra);
        txtcontra.setBounds(10, 70, 90, 26);

        textboxus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textboxusActionPerformed(evt);
            }
        });
        getContentPane().add(textboxus);
        textboxus.setBounds(100, 40, 100, 20);
        getContentPane().add(textboxpw);
        textboxpw.setBounds(100, 70, 100, 20);

        btnolvide.setBackground(new java.awt.Color(0, 51, 204));
        btnolvide.setForeground(new java.awt.Color(255, 255, 255));
        btnolvide.setText("olvide mi contraseña");
        btnolvide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnolvideActionPerformed(evt);
            }
        });
        getContentPane().add(btnolvide);
        btnolvide.setBounds(30, 140, 160, 23);

        btning.setBackground(new java.awt.Color(51, 51, 51));
        btning.setForeground(new java.awt.Color(255, 255, 255));
        btning.setText("ingresar");
        btning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningActionPerformed(evt);
            }
        });
        getContentPane().add(btning);
        btning.setBounds(70, 110, 82, 23);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido a Login Pokedex");
        jLabel1.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 197, 21);

        txtuser1.setForeground(new java.awt.Color(255, 255, 255));
        txtuser1.setText("usuario");
        getContentPane().add(txtuser1);
        txtuser1.setBounds(10, 40, 80, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\W10\\Documents\\NetBeansProjects\\pokedexp2b\\src\\main\\java\\imagenes\\login1.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -20, 270, 270);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(40, 160, 160, 2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_btningActionPerformed

    private void textboxusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textboxusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textboxusActionPerformed

    private void btnolvideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnolvideActionPerformed
        // TODO add your handling code here:
        RecuperarContraseña rc = new RecuperarContraseña();
        rc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnolvideActionPerformed

    
    public void login(){
        
        String user= textboxus.getText();
        String pwd=String.valueOf(textboxpw.getPassword());
        
        Usuario usu= new Usuario();
        
        UsuarioJDBC us= new UsuarioJDBC();

        
        usu.setUsername(user);
        usu.setPassword(pwd);
        
             
         if(us.select_validacion(usu)){
             
             
             JOptionPane.showMessageDialog(null, "bienvenido "+user);
             ventanapokedex poke = new ventanapokedex();
             poke.setVisible(true);
              this.dispose();
             
         }
         else{
             
             JOptionPane.showMessageDialog(null, "Usuario o Contraseña Incorrecta");
             textboxus.setText(null);
             textboxpw.setText(null);
         }
        
        
        
        
        
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btning;
    private javax.swing.JButton btnolvide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField textboxpw;
    public static javax.swing.JTextField textboxus;
    private javax.swing.JLabel txtcontra;
    private javax.swing.JLabel txtuser1;
    // End of variables declaration//GEN-END:variables
}
